/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasiEntryDataMahasiswa;
import java.awt.Desktop;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Vira
 */
public class Form_Mahasiswa extends javax.swing.JFrame {
    KoneksiDB koneksi = new KoneksiDB();

    /**
     * Creates new form Form_Transaksi
     */
    public Form_Mahasiswa() {
        initComponents();
        tgl();
        tampil();
    }
    private void tgl (){
        Date ys = new Date();
        SimpleDateFormat s  = new SimpleDateFormat("yyyy-MM-dd");
        tgl.setText(s.format(ys));
    }
    public void kosong (){
        nim.setText("");
        nama.setText("");
        alamat.setText("");
        jurusan.setSelectedIndex(-0);
        semester.setText("");
        nim.requestFocus();
    }
    public void tampil(){
        DefaultTableModel tabel1= new DefaultTableModel();
        tabel1.addColumn("NIM");
        tabel1.addColumn("Nama");
        tabel1.addColumn("Jenis Kelamin");
        tabel1.addColumn("Alamat");
        tabel1.addColumn("Jurusan");
        tabel1.addColumn("Semester");

        tabel.setModel(tabel1); 
        String cari = txt_cari.getText();
        try {
            ResultSet res= koneksi.stat.executeQuery("select * from mahasiswa where nama like '%"+cari+"%'");           
            while(res.next()){
                tabel1.addRow(new Object[] {
                    res.getString("nim"),
                    res.getString("nama"),
                    res.getString("jenis_kelamin"),
                    res.getString("alamat"),
                    res.getString("jurusan"),
                    res.getString("semester"),
                });
                    tabel.setModel(tabel1);
                }
            } catch (Exception e) {
            
            }    
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        semester = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btn_keluar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_batal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nim = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        btn_simpan = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();
        jk_laki = new javax.swing.JRadioButton();
        jk_perempuan = new javax.swing.JRadioButton();
        jurusan = new javax.swing.JComboBox<>();
        tgl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        semester.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        semester.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                semesterMouseClicked(evt);
            }
        });
        semester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterActionPerformed(evt);
            }
        });
        semester.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                semesterKeyReleased(evt);
            }
        });

        alamat.setColumns(20);
        alamat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("JENIS KELAMIN");

        btn_keluar.setBackground(new java.awt.Color(255, 255, 51));
        btn_keluar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_keluar.setForeground(new java.awt.Color(255, 0, 0));
        btn_keluar.setText("LOGOUT");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("JURUSAN");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("SEMESTER");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("FORM MAHASISWA");

        btn_hapus.setBackground(new java.awt.Color(255, 255, 51));
        btn_hapus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 0, 51));
        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_ubah.setBackground(new java.awt.Color(255, 255, 51));
        btn_ubah.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_ubah.setForeground(new java.awt.Color(255, 0, 51));
        btn_ubah.setText("UBAH");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("ALAMAT");

        nama.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nama.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                namaCaretUpdate(evt);
            }
        });
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                namaKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("NAMA");

        btn_batal.setBackground(new java.awt.Color(255, 255, 51));
        btn_batal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_batal.setForeground(new java.awt.Color(255, 0, 51));
        btn_batal.setText("RESET");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("NIM");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Cari Berdasarkan Nama :");

        nim.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        tabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama", "Jenis Kelamin", "Alamat", "Jurusan", "Semester"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        btn_simpan.setBackground(new java.awt.Color(255, 255, 51));
        btn_simpan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_simpan.setForeground(new java.awt.Color(255, 0, 51));
        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        txt_cari.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });

        jk_laki.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jk_laki.setText("LAKI-LAKI");

        jk_perempuan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jk_perempuan.setText("PEREMPUAN");

        jurusan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teknik Industri", "Teknik Kimia", "D3 Teknik Kimia", "Informatika", "Sistem Informasi" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_keluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(267, 267, 267))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jk_laki, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jk_perempuan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nama)
                                .addComponent(nim)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(69, 69, 69)
                                    .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(semester, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(jurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btn_keluar)
                    .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jurusan))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jk_laki)
                        .addComponent(jk_perempuan)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_simpan)
                        .addComponent(btn_ubah))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_hapus)
                        .addComponent(btn_batal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        String NIM = nim.getText();
        String NAMA = nama.getText();
        String JENISKELAMIN = null;
if (jk_laki.isSelected()) {
    JENISKELAMIN = "Laki-Laki";
} else if (jk_perempuan.isSelected()) {
    JENISKELAMIN = "Perempuan";
}
String JURUSAN  = (String) jurusan.getSelectedItem();
String SEMESTER = semester.getText();
String ALAMAT   = alamat.getText();
        if(NIM.equals("")){
            JOptionPane.showMessageDialog(null, "NIM Harap Diisi");
            nim.requestFocus();
            return;
        }
        if(NAMA.equals("")){
            JOptionPane.showMessageDialog(null, "Nama Pelanggan Harap Diisi");
            nama.requestFocus();
            return;
        }
        if(ALAMAT.equals("")){
            JOptionPane.showMessageDialog(null, "Alamat Harap Diisi");
            alamat.requestFocus();
            return;
        }
        if(JURUSAN.equals("")){
            JOptionPane.showMessageDialog(null, "Jurusan Harap Diisi");
            jurusan.requestFocus();
            return;
        }
        if(SEMESTER.equals("")){
            JOptionPane.showMessageDialog(null, "Semester Harap Diisi");
            semester.requestFocus();
            return;
        }
            else {}
            int konfirm = JOptionPane.showConfirmDialog(this, "Anda Yakin Ingin Menambah Data ?", "Konfirmasi",
                    JOptionPane.YES_NO_OPTION);
             if (konfirm == 0){
                JOptionPane.showMessageDialog(null, "Proses Penyimpanan ?");
        {
        String SQL = "insert into mahasiswa(nim,nama,jenis_kelamin,alamat,jurusan,semester) values ('"+NIM+"','"+NAMA+"', '"+JENISKELAMIN+"','"+ALAMAT+"','"+JURUSAN+"','"+SEMESTER+"')";
        System.out.println(SQL);
        try {
            koneksi.stat.executeUpdate(SQL);
            JOptionPane.showMessageDialog(rootPane, "Data Berhasil Di Tambahkan");
            tampil();
            kosong();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data Gagal Di Tambahkan");
        }
    }
}
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
         String NIM = nim.getText();
        String NAMA = nama.getText();
        String JENISKELAMIN = null;
if (jk_laki.isSelected()) {
    JENISKELAMIN = "Laki-Laki";
} else if (jk_perempuan.isSelected()) {
    JENISKELAMIN = "Perempuan";
}
String JURUSAN  = (String) jurusan.getSelectedItem();
String SEMESTER = semester.getText();
String ALAMAT   = alamat.getText();
            int konfirm = JOptionPane.showConfirmDialog(this, "Anda Yakin Ingin Mengubah Data ?", "Konfirmasi",
                    JOptionPane.YES_NO_OPTION);
             if (konfirm == 0){
                JOptionPane.showMessageDialog(null, "Proses Mengubah ?");
        {
        String SQL = "update mahasiswa set nim='"+NIM+"',nama='"+NAMA+"',jenis_kelamin='"+JENISKELAMIN+"',alamat='"+ALAMAT+"',jurusan='"+JURUSAN+"',semester='"+SEMESTER+"'";
        System.out.println(SQL);
        try {
            koneksi.stat.executeUpdate(SQL);
            JOptionPane.showMessageDialog(rootPane, "Data Berhasil Di Ubah");
            tampil();
            kosong();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data Gagal Di Ubah");
        }
    }
}
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        String NIM      = nim.getText();
            int konfirm = JOptionPane.showConfirmDialog(this, "Anda Yakin Ingin Menghapus Data ?", "Konfirmasi",
                    JOptionPane.YES_NO_OPTION);
             if (konfirm == 0){
                JOptionPane.showMessageDialog(null, "Proses Menghapus ?");
        {
        String SQL = "delete from mahasiswa where nim=('"+ NIM +"')";
        System.out.println(SQL);
        try {
            koneksi.stat.executeUpdate(SQL);
            JOptionPane.showMessageDialog(rootPane, "Data Berhasil Di Hapus");
            tampil();
            kosong();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data Gagal Di Hapus");
        }
    }
}
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
       kosong();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        Form_Login login = new Form_Login();
        login.setVisible(true);
        dispose();
        login.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void semesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterActionPerformed

    private void semesterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semesterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterMouseClicked

    private void semesterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_semesterKeyReleased
        /* TODO add your handling code here:
        berat = Integer.parseInt(semester.getText());
        harga = 5000;
        total_bayar = berat*5000;
        txt_ttlbyr.setText(String.valueOf(total_bayar));
        txt_harga.setText(String.valueOf(harga));*/
    }//GEN-LAST:event_semesterKeyReleased

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
        // TODO add your handling code here:
        tampil();
    }//GEN-LAST:event_txt_cariKeyReleased

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        nim.setText(tabel.getValueAt(tabel.getSelectedRow(), 0).toString());
        nama.setText(tabel.getValueAt(tabel.getSelectedRow(), 1).toString());
        if ("LAKI-LAKI".equals(tabel.getValueAt(tabel.getSelectedRow(), 2).toString())) {
        jk_laki.setSelected(true);
        } else {
        jk_perempuan.setSelected(true);
        }
        alamat.setText(tabel.getValueAt(tabel.getSelectedRow(), 3).toString());
        jurusan.setSelectedItem(tabel.getValueAt(tabel.getSelectedRow(), 4).toString());
        semester.setText(tabel.getValueAt(tabel.getSelectedRow(), 5).toString());
        
    }//GEN-LAST:event_tabelMouseClicked

    private void namaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_namaCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_namaCaretUpdate

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_namaActionPerformed

    private void namaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaKeyReleased
        /* TODO add your handling code here:
        String No_antri = nama.getText();
         try{
            com.mysql.jdbc.Statement statement=(com.mysql.jdbc.Statement)koneksi.stat.getConnection().createStatement();
            ResultSet res=statement.executeQuery("select * from tabel_pemesanan where No_antrian='"+No_antri+"'");
            while(res.next()){
                nama.setText(res.getString("No_antrian"));
                txt_namapel.setText(res.getString(3));
                alamat.setText(res.getString(4));
                txt_notlp.setText(res.getString(5));
                semester.setText(res.getString(6));
                txt_harga.setText(res.getString(7));
                txt_ttlbyr.setText(res.getString(8));            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Salah");
        }*/
    }//GEN-LAST:event_namaKeyReleased

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Transaksi().setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JRadioButton jk_laki;
    private javax.swing.JRadioButton jk_perempuan;
    private javax.swing.JComboBox<String> jurusan;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nim;
    private javax.swing.JTextField semester;
    private javax.swing.JTable tabel;
    private javax.swing.JLabel tgl;
    private javax.swing.JTextField txt_cari;
    // End of variables declaration//GEN-END:variables
}
